version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
# - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../var/www/html:/usr/share/nginx/html
    container_name: animesign_nginx